site_name: DOC316
site_url: https://doc316.readthedocs.io/
repo_url: https://github.com/FZR95/Doc316/tree/MkDocs
repo_name: Doc316
nav:
  - 学习路径:
      - IOT:
        - 开始: learningroute/IOT/index.md
        - 前言与技术路线: learningroute/IOT/面向初学者的物联网全栈开发指南/面向初学者的物联网全栈开发指南 - 1 -.md
        - 硬件侧: learningroute/IOT/面向初学者的物联网全栈开发指南/面向初学者的物联网全栈开发指南 - 2 -.md
        - IOT平台和MQTT协议: learningroute/IOT/面向初学者的物联网全栈开发指南/面向初学者的物联网全栈开发指南 - 3 -.md
        - 硬件侧上云: learningroute/IOT/面向初学者的物联网全栈开发指南/面向初学者的物联网全栈开发指南 - 4 -.md
        - uniCloud对接: learningroute/IOT/面向初学者的物联网全栈开发指南/面向初学者的物联网全栈开发指南 - 5 -.md
        - uni-app起步: learningroute/IOT/面向初学者的物联网全栈开发指南/面向初学者的物联网全栈开发指南 - 6 -.md
        - MQTT: learningroute/IOT/MQTT.md
      - 基于卡尔曼滤波器的电子秤:
        - 开始: learningroute/基于卡尔曼滤波器的电子秤/index.md
        - 电桥: learningroute/基于卡尔曼滤波器的电子秤/bridge.md
        - 卡尔曼算法: learningroute/基于卡尔曼滤波器的电子秤/kalman.md
        - 电子秤: learningroute/基于卡尔曼滤波器的电子秤/scale.md
  - 知识技巧:
      - 电子管: tricks/电子管/电子管.md
      - MLSA: tricks/MLSA/index.md
      - 滤波器: tricks/滤波器/index.md
      - PID: tricks/PID/pid.md
      - 无线定位技术: tricks/无线定位/无线定位.md
  - 资源列表:
      - 软件资源: resource/resource.md
      - 网站资源: resource/link.md
  - 参与编辑: tutorial/tutorial.md
  - 关于:
#      - 介绍: index.md
      - 修订记录: about/revision.md

theme:
  name: material
  language: zh
  logo: images/favicon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - header.autohide
    - navigation.instant
    #    - navigation.tabs
    - navigation.sections
#    - navigation.top
plugins:
  - search:
      separator: '[\s\u200b\-]'

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - tables
  - md_in_html
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      #      permalink: true
      toc_depth: 4

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js